### ISSUE TITLE
Overly strict validation of digital signals

### ISSUE THREAD

**Issue by Cody-G** [HolyLab/ImagineInterface#41]
It was brought to my attention that the way we're currently validating digital signals may be too restrictive.  We require that TTL signals begin and end LOW.

I did it this makes the finding and counting of pulses (like camera and laser triggers) less ambiguous and a big easier to code.  But I don't think Imagine is currently using any such requirement, so maybe it's better to remove that restriction.

@kdw503 do you see any benefits to forcing digital signals to begin LOW?  One concern I have is that the DAQ might leave the digital line in the same state after the recording is over.  So if the last sample is HIGH then the device will stay triggered.   If that's true it could definitely cause some problems (like an extremely long exposure time on the last camera trigger)

**Comment by kdw503** [comment]
> I have is that the DAQ might leave the digital line in the same state after the recording is over. So if the last sample is HIGH then the device will stay triggered.

Now Imagine works like this. So, you want the DAQ make every digital line be LOW before and after the recording? If so, I'm ok with this.

**Comment by Cody-G** [comment]
I think that would make sense.  Then I could remove any restrictions on the waveform itself.  We should probably also do something extra for analog outputs.  I think it's okay to leave the DAQ set at the last AO sample, but moving it to the _first_ AO sample could be dangerous if we do it too quickly (i.e. the piezo is at 0um when the user presses "record", but the first AO sample in the command is 500um).  Before starting the recording I think we should do a `moveTo` command with the first sample of the AO sequence.  I'm forgetting, maybe that function isn't called `moveTo` but Imagine does have a safe piezo movement function accepting a single sample.

**Comment by kdw503** [comment]
> I think it's okay to leave the DAQ set at the last AO sample, but moving it to the first AO sample could be dangerous if we do it too quickly

Yes, you are right. This is already implemented in current Imagine. When we press 'apply' button it move to the first position of piezo wave sequence.

**Comment by Cody-G** [comment]
Great!  Then I will remove this constraint from ImagineInterface.
