### ISSUE TITLE
Channel confliction

### ISSUE THREAD

**Issue by HaoyangRong** [HolyLab/ImagineInterface#59]
When loading JSON file using Imagine, an error message popped up
```
'AI2' channels is already reserved as a 'galvo1 monitor' signal
'AI3' channels is already reserved as a 'galvo2 monitor' signal
```
And these two channels can be found in the JSON file`{"analog waveform":{"analogin1":{"daq channel":"AI2"}`, `"analogin2":{"daq channel":"AI3"}`
@Cody-G @kdw503

**Comment by Cody-G** [comment]
Yes, this was a planned transition for supporting galvo control on OCPI2.  See these two issues:

https://github.com/HolyLab/Imagine/issues/44
https://github.com/HolyLab/ImagineInterface/issues/47

Dae Woo has already updated the waveform branch of Imagine, but I haven't updated the validation code of ImagineInterface to reflect the change.  I'll get that update merged asap.  Any other AI channels should work as before.
