### ISSUE TITLE
parse_ai gives Error about "x translation in pixels"

### ISSUE THREAD

**Issue by Callahanra** [HolyLab/ImagineInterface#62]
Hi!

I'm trying to use this to check out my analog physiology input. The .imagine, .json and .di files are all in the same folder.
  
julia> parse_ai("Vr_f2_smalltip_t1.ai")
       ERROR: KeyError: key "x translation in pixels" not found

Thanks!!

**Comment by Cody-G** [comment]
Ah, this is because ImagineFormat needs another update for recent changes by @kdw503.  I probably won't get to that before Sunday.  For now it should work if you delete the translation / rotation line entries.  (Those are only relevant if you were using both cameras anyway)

**Comment by mdhe1248** [comment]
Has this issue been solved? I have the same problem.

**Comment by Cody-G** [comment]
Not solved yet.  It requires a change to ImagineFormat pretty similar to the one you implemented just a couple of days ago.  I should get to it in the next couple of days, but if you decide to work on it let me know.

**Comment by mdhe1248** [comment]
Can I make a temporary solution? 
We can just add those keys and values.

**Comment by mdhe1248** [comment]
I will change. 
I tested it. Loading works with or with out the keys and values in the imagine file, meaning that it is compatible to both older and newer imagine files.

**Comment by mdhe1248** [comment]
I made this branch. "jerry/mismatchCorrection". I will merge in a few hours or days.

**Comment by Cody-G** [comment]
This was merged now, but you may still need to checkout the master branch of ImagineFormat if you get this error.
