### ISSUE TITLE
Question about di.

### ISSUE THREAD

**Issue by mdhe1248** [HolyLab/ImagineInterface#65]
Is the sampling rate of .di half of that of .ai?

**Comment by Cody-G** [comment]
It's the same sampling rate, but the samples are stored as 8-bit bool
values rather than 16 bit int like the .ai file

**Comment by mdhe1248** [comment]
Thanks!

**Comment by Cody-G** [comment]
Oh sorry, I just realized I answered that incorrectly.  The samples of the (up to 8) digital input channels are "bit-packed", meaning that there are 8 samples (one from each channel) compressed into a single 8-bit value.  In Julia this can be manipulated easily using BitArrays. 
 See this line for how it's done when w parse the .di file:
 https://github.com/HolyLab/ImagineInterface/blob/master/src/parse.jl#L183

**Comment by mdhe1248** [comment]
This is helpful Cody.
Thanks!

**Comment by mdhe1248** [comment]
```jl
A = Mmap.mmap(f, BitArray, (8,nsamples))` #we need all 8 bits even if the user didn't ask for 8 channels of DI
```
What does it happen if I change the number 8 into other values?

**Comment by Cody-G** [comment]
>What does it happen if I change the number 8 into other values?

Then the sample array will be mapped incorrectly and samples will be mixed across channels.  It's similar to what happens if you memory map the .ai file with the wrong number of channels.

**Comment by mdhe1248** [comment]
Does it apply to OCPI1 too?

**Comment by Cody-G** [comment]
If you are using the new version of Imagine then yes.

**Comment by mdhe1248** [comment]
Okay. Thanks!
